// <auto-generated />
namespace MVCMusic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddOneToMany_Customer_Reviewed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddOneToMany_Customer_Reviewed));
        
        string IMigrationMetadata.Id
        {
            get { return "201712022128035_AddOneToMany_Customer_Reviewed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
